## Importing The Important Libraries

In [1]:
import numpy as np #for Numerical Operation
import pandas as pd #for dataframe
import matplotlib.pyplot as plt #For visualization
import seaborn as sns #for Advanced Visulaization
from math import radians, sin, cos, sqrt, atan2  #For Performing Math operations
import warnings #handling Warnings
import folium #Geospatial visualization

# Ignore/Filter out warning messages
warnings.filterwarnings("ignore")

from sklearn.impute import SimpleImputer #for filling missing values
from sklearn.preprocessing import StandardScaler #used for scale the features
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder # for text to numerical values
from sklearn.pipeline import Pipeline #ML Flow
from sklearn.compose import ColumnTransformer #supporting Pipeline
from sklearn.impute import KNNImputer #Filling values with neighbors
from sklearn.model_selection import train_test_split # for splitting the data

## Loading the Data

In [2]:
df = pd.read_csv("finalTrain.csv")

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

## EDA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  object
 1   Delivery_person_ID           45584 non-null  object
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  object
 9   Time_Orderd                  43853 non-null  object
 10  Time_Order_picked            45584 non-null  object
 11  Weather_conditions           44968 non-null  object
 12  Road_traffic_density         44983 non-null  object
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  object
 15  Type_of_vehicle              45584 non-null  object
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  object
 18  City                         44384 non-null  object
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), object(11)
memory usage: 7.0+ MB

In [5]:
df.shape

(45584, 20)

In [6]:
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken (min)
count,43730.000000,43676.000000,45584.000000,45584.000000,45584.000000,45584.000000,45584.000000,44591.000000,45584.000000
mean,29.566911,4.633774,17.017948,70.229684,17.465480,70.844161,1.023385,0.744635,26.293963
std,5.815064,0.334744,8.185674,22.885575,7.335562,21.120578,0.839055,0.572510,9.384298
min,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,0.000000,0.000000,10.000000
25%,25.000000,4.500000,12.933284,73.170000,12.988453,73.280000,0.000000,0.000000,19.000000
50%,30.000000,4.700000,18.551440,75.897963,18.633934,76.002574,1.000000,1.000000,26.000000
75%,35.000000,4.900000,22.728163,78.044095,22.785049,78.107044,2.000000,1.000000,32.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,3.000000,3.000000,54.000000

In [7]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

## NOw there are two way to check the unique value of each columns:
## 1. Check manually (df["column_name"].unique())
## 2. Check automatically(below code)

In [9]:
for i in df.columns:
    print(f" no. of unique value in {i} is : {df[i].nunique()}")
    print("__________________________________")
    if (df[i].nunique()) < 8:
        print(f"         unique value are : {df[i].unique()}")
        print(".........................")
    else:
        pass

 no. of unique value in ID is : 45584
__________________________________
 no. of unique value in Delivery_person_ID is : 1320
__________________________________
 no. of unique value in Delivery_person_Age is : 22
__________________________________
 no. of unique value in Delivery_person_Ratings is : 28
__________________________________
 no. of unique value in Restaurant_latitude is : 657
__________________________________
 no. of unique value in Restaurant_longitude is : 518
__________________________________
 no. of unique value in Delivery_location_latitude is : 4373
__________________________________
 no. of unique value in Delivery_location_longitude is : 4373
__________________________________
 no. of unique value in Order_Date is : 44
__________________________________
 no. of unique value in Time_Orderd is : 176
__________________________________
 no. of unique value in Time_Order_picked is : 193
__________________________________
 no. of unique value in Weather_conditions is : 6
__________________________________
         unique value are : ['Fog' 'Stormy' 'Sandstorms' 'Windy' 'Cloudy' 'Sunny' nan]
.........................
 no. of unique value in Road_traffic_density is : 4
__________________________________
         unique value are : ['Jam' 'High' 'Medium' 'Low' nan]
.........................
 no. of unique value in Vehicle_condition is : 4
__________________________________
         unique value are : [2 1 0 3]
.........................
 no. of unique value in Type_of_order is : 4
__________________________________
         unique value are : ['Snack' 'Meal' 'Drinks' 'Buffet']
.........................
 no. of unique value in Type_of_vehicle is : 4
__________________________________
         unique value are : ['motorcycle' 'scooter' 'electric_scooter' 'bicycle']
.........................
 no. of unique value in multiple_deliveries is : 4
__________________________________
         unique value are : [ 3.  1.  0. nan  2.]
.........................
 no. of unique value in Festival is : 2
__________________________________
         unique value are : ['No' 'Yes' nan]
.........................
 no. of unique value in City is : 3
__________________________________
         unique value are : ['Metropolitian' 'Urban' 'Semi-Urban' nan]
.........................
 no. of unique value in Time_taken (min) is : 45
__________________________________

## Get the Information of every Features

In [10]:
feature = []
dtypes = []
count = []
unique = []
missing = []
missing_percentage = []

for column in df.columns:
    feature.append(column)
    dtypes.append(df[column].dtypes)
    count.append(len(df[column]))
    missing.append(df[column].isnull().sum())
    unique.append(df[column].nunique())
    missing_percentage.append((df[column].isnull().sum() / df.shape[0]) * 100)

dataframe = pd.DataFrame({'feature':feature,
                         'dtypes':dtypes,
                         'missing':missing,
                         'nunique':unique,
                         'missing_percentage':missing_percentage,
                         'count':count})
dataframe.set_index("feature")

,dtypes,missing,nunique,missing_percentage,count
feature,,,,,
ID,object,0,45584,0.000000,45584
Delivery_person_ID,object,0,1320,0.000000,45584
Delivery_person_Age,float64,1854,22,4.067217,45584
Delivery_person_Ratings,float64,1908,28,4.185679,45584
Restaurant_latitude,float64,0,657,0.000000,45584
Restaurant_longitude,float64,0,518,0.000000,45584
Delivery_location_latitude,float64,0,4373,0.000000,45584
Delivery_location_longitude,float64,0,4373,0.000000,45584
Order_Date,object,0,44,0.000000,45584
Time_Orderd,object,1731,176,3.797385,45584
Time_Order_picked,object,0,193,0.000000,45584
Weather_conditions,object,616,6,1.351351,45584
Road_traffic_density,object,601,4,1.318445,45584
Vehicle_condition,int64,0,4,0.000000,45584
Type_of_order,object,0,4,0.000000,45584
Type_of_vehicle,object,0,4,0.000000,45584
multiple_deliveries,float64,993,4,2.178396,45584
Festival,object,228,2,0.500176,45584
City,object,1200,3,2.632503,45584
Time_taken (min),int64,0,45,0.000000,45584

In [11]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

## Feature Engineering

In [12]:
df.drop(df[["ID","Delivery_person_Age"]],axis=1,inplace=True)
df.head()

,Delivery_person_ID,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,DEHRES17DEL01,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,KOCRES16DEL01,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,PUNERES13DEL03,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,LUDHRES15DEL02,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,KNPRES14DEL02,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [13]:
df["Order_Date"]

0        12-02-2022
1        13-02-2022
2        04-03-2022
3        13-02-2022
4        14-02-2022
            ...
45579    24-03-2022
45580    16-02-2022
45581    11-03-2022
45582    07-03-2022
45583    02-03-2022
Name: Order_Date, Length: 45584, dtype: object

In [14]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"],format="%d-%m-%Y", errors='coerce')

In [15]:
df["Order_Date"]

0       2022-02-12
1       2022-02-13
2       2022-03-04
3       2022-02-13
4       2022-02-14
           ...
45579   2022-03-24
45580   2022-02-16
45581   2022-03-11
45582   2022-03-07
45583   2022-03-02
Name: Order_Date, Length: 45584, dtype: datetime64[ns]

In [16]:
df["year"] = df["Order_Date"].dt.year
df["month"] = df["Order_Date"].dt.month
df["day"] = df["Order_Date"].dt.day

In [17]:
df.head()

,Delivery_person_ID,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,...,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),year,month,day
0,DEHRES17DEL01,4.2,30.327968,78.046106,30.397968,78.116106,2022-02-12,21:55,22:10,Fog,...,2,Snack,motorcycle,3.0,No,Metropolitian,46,2022,2,12
1,KOCRES16DEL01,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,14:55,15:05,Stormy,...,1,Meal,motorcycle,1.0,No,Metropolitian,23,2022,2,13
2,PUNERES13DEL03,4.7,18.562450,73.916619,18.652450,74.006619,2022-03-04,17:30,17:40,Sandstorms,...,1,Drinks,scooter,1.0,No,Metropolitian,21,2022,3,4
3,LUDHRES15DEL02,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,09:20,09:30,Sandstorms,...,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2022,2,13
4,KNPRES14DEL02,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,19:50,20:05,Fog,...,1,Snack,scooter,1.0,No,Metropolitian,41,2022,2,14

In [18]:
df.drop("Order_Date",axis=1,inplace=True)
df.head()

,Delivery_person_ID,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),year,month,day
0,DEHRES17DEL01,4.2,30.327968,78.046106,30.397968,78.116106,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,2022,2,12
1,KOCRES16DEL01,4.7,10.003064,76.307589,10.043064,76.347589,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,2022,2,13
2,PUNERES13DEL03,4.7,18.562450,73.916619,18.652450,74.006619,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,2022,3,4
3,LUDHRES15DEL02,4.3,30.899584,75.809346,30.919584,75.829346,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2022,2,13
4,KNPRES14DEL02,4.7,26.463504,80.372929,26.593504,80.502929,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,2022,2,14

In [19]:
df.isnull().sum()

Delivery_person_ID                0
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
year                              0
month                             0
day                               0
dtype: int64

In [20]:
df.dropna(subset=["Time_Orderd"],inplace=True)

In [21]:
df["Time_Orderd"] = df["Time_Orderd"].str.replace(".", ":")

In [22]:
df["Time_Orderd"].sample(15)

25558          23:45
29309          14:40
178            20:35
18444          17:45
9266     0:958333333
22063          23:40
42208          23:30
8154           21:35
11114          18:35
1727             0:5
4626           18:50
41104          23:30
40436          10:55
28265          23:45
32733          22:10
Name: Time_Orderd, dtype: object

In [23]:
# define a Lambda function with error Handling

def extract_time(x):
    try:
        return x.split(':')[0] + ':' + x.split(':')[1][:2]
    except IndexError:
        return "00:00"
df["Time_Orderd"] = df["Time_Orderd"].apply(extract_time)

# Suppose x is string like "12:34" 
#  x.split(':') mean Splits the string by :
# x.split(':')[0] means Gets the hour part: 12
# x.split(':')[1][:2] means take the first 2 characters of the minutes. like extract_time("12:34:56") Output: "12:34"

In [24]:
df.head()

,Delivery_person_ID,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),year,month,day
0,DEHRES17DEL01,4.2,30.327968,78.046106,30.397968,78.116106,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,2022,2,12
1,KOCRES16DEL01,4.7,10.003064,76.307589,10.043064,76.347589,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,2022,2,13
2,PUNERES13DEL03,4.7,18.562450,73.916619,18.652450,74.006619,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,2022,3,4
3,LUDHRES15DEL02,4.3,30.899584,75.809346,30.919584,75.829346,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2022,2,13
4,KNPRES14DEL02,4.7,26.463504,80.372929,26.593504,80.502929,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,2022,2,14

In [25]:
#convert the time_Orderd column to a time data type
df["Time_Orderd"] = pd.to_datetime(df["Time_Orderd"],format='%H:%M:%S',errors="ignore")

In [26]:
df.head()

,Delivery_person_ID,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),year,month,day
0,DEHRES17DEL01,4.2,30.327968,78.046106,30.397968,78.116106,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,2022,2,12
1,KOCRES16DEL01,4.7,10.003064,76.307589,10.043064,76.347589,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,2022,2,13
2,PUNERES13DEL03,4.7,18.562450,73.916619,18.652450,74.006619,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,2022,3,4
3,LUDHRES15DEL02,4.3,30.899584,75.809346,30.919584,75.829346,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2022,2,13
4,KNPRES14DEL02,4.7,26.463504,80.372929,26.593504,80.502929,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,2022,2,14

In [27]:
df["TimeOrder_Hour"] = df["Time_Orderd"].str.split(":",expand=True)[0]

# Replacing 0 with 00 because both indicate 24th hour
df["TimeOrder_Hour"] = df["TimeOrder_Hour"].replace('0','00')
#Changing the DataType
df["TimeOrder_Hour"] = df["TimeOrder_Hour"].astype('int32')

In [28]:
#Order Minute
df["TimeOrder_min"] = df["Time_Orderd"].str.split(':',expand=True)[1]
#Changing the datatype
df["TimeOrder_min"] = df["TimeOrder_min"].astype('int32')

df.head()

In [29]:
df["Time_Order_picked"] = df["Time_Order_picked"].str.replace(".", ":")

In [30]:
def extract_time(x):
    try:
        return x.split(':')[0] + ':' + x.split(':')[1][:2]
    except IndexError:
        return "00:00"
df["Time_Order_picked"] = df["Time_Order_picked"].apply(extract_time)

In [31]:
df["Time_Order_picked"] = pd.to_datetime(df["Time_Order_picked"],format='%H:%M:%S',errors="ignore")

In [32]:
df["Time_Order_picked_Hour"] = df["Time_Order_picked"].str.split(":",expand=True)[0]

#Changing the DataType
df["Time_Order_picked_Hour"] = df["Time_Order_picked_Hour"].astype('int32')

In [33]:
#Order Minute
df["Time_Order_picked_min"] = df["Time_Order_picked"].str.split(':',expand=True)[1]
#Changing the datatype
df["Time_Order_picked_min"] = df["Time_Order_picked_min"].astype('int32')

# Extracting city from delivery_person_id

In [34]:
# Splitting the Delivery_person_id on the bases of "RES", This will give us the city name of delivery

df["Delivery_city"] = df["Delivery_person_ID"].str.split("RES",expand=True)[0]

In [35]:
df.head()

,Delivery_person_ID,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,...,City,Time_taken (min),year,month,day,TimeOrder_Hour,TimeOrder_min,Time_Order_picked_Hour,Time_Order_picked_min,Delivery_city
0,DEHRES17DEL01,4.2,30.327968,78.046106,30.397968,78.116106,21:55,22:10,Fog,Jam,...,Metropolitian,46,2022,2,12,21,55,22,10,DEH
1,KOCRES16DEL01,4.7,10.003064,76.307589,10.043064,76.347589,14:55,15:05,Stormy,High,...,Metropolitian,23,2022,2,13,14,55,15,5,KOC
2,PUNERES13DEL03,4.7,18.562450,73.916619,18.652450,74.006619,17:30,17:40,Sandstorms,Medium,...,Metropolitian,21,2022,3,4,17,30,17,40,PUNE
3,LUDHRES15DEL02,4.3,30.899584,75.809346,30.919584,75.829346,09:20,09:30,Sandstorms,Low,...,Metropolitian,20,2022,2,13,9,20,9,30,LUDH
4,KNPRES14DEL02,4.7,26.463504,80.372929,26.593504,80.502929,19:50,20:05,Fog,Jam,...,Metropolitian,41,2022,2,14,19,50,20,5,KNP

In [36]:
df["Delivery_person_Ratings"].isnull().sum()

np.int64(268)

Filling the null value with the mean of that person ID

In [37]:
rating_map = round(df.groupby("Delivery_person_ID")["Delivery_person_Ratings"].mean(),1).to_dict()
df["Delivery_person_Ratings"] = df["Delivery_person_Ratings"].fillna(df["Delivery_person_ID"].map(rating_map))
#fillup the missing value in delivery_person_ratings with the help of mean value of every delivery_person_id

In [38]:
df["Delivery_person_Ratings"].isnull().sum()

np.int64(0)

In [39]:
folium.Map(tiles="cartodb positron")

Now Calculate the distance between two points on a sphere(like Earth),we can use the Haversine formula

In [40]:
import math
def distance(lat1, lon1, lat2, lon2):
    #convert the latitude and longitude to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    #Haversine Formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    R = 6371.0 #Earth radius in Km
    dist = R*c
    return dist
df['distance'] = df.apply(lambda row: distance(row['Restaurant_latitude'], row['Restaurant_longitude'], row['Delivery_location_latitude'], row['Delivery_location_longitude']), axis=1)

In [41]:
df["distance"].head()

0    10.280582
1     6.242319
2    13.787860
3     2.930258
4    19.396618
Name: distance, dtype: float64

In [42]:
df.groupby(['Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude','Delivery_location_longitude'])['distance'].max().head(40)

Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  Delivery_location_longitude
-30.902872           75.826808             30.972872                   75.896808                      6880.272782
                                           31.012872                   75.936808                      6884.726399
-30.899584           75.809346             30.929584                   75.839346                      6875.090529
                                           30.949584                   75.859346                      6877.315724
                                           30.959584                   75.869346                      6878.428563
-30.895817           75.813112             30.905817                   75.823112                      6872.028240
                                           30.965817                   75.883112                      6878.703822
                                           31.005817                   75.923112                      6883.157441
-30.893244           75.821817             30.933244                   75.861817                      6874.793094
-30.892978           75.821847             30.902978                   75.831847                      6871.396875
-30.885915           75.788259             30.945915                   75.848259                      6875.388718
-30.885814           75.786976             30.965814                   75.866976                      6877.592421
-30.873988           75.842739             30.923988                   75.892739                      6871.623435
                                           30.963988                   75.932739                      6876.075767
-30.372202           78.077151             30.432202                   78.137151                      6761.144219
-30.361281           78.068022             30.471281                   78.178022                      6764.282269
-30.346994           78.062543             30.396994                   78.112543                      6754.425359
                                           30.426994                   78.142543                      6757.764433
-30.328174           78.049117             30.348174                   78.069117                      6746.902397
-30.327968           78.046106             30.347968                   78.066106                      6746.856584
-30.319528           78.040267             30.379528                   78.100267                      6749.430062
                                           30.429528                   78.150267                      6754.996842
-27.201725           78.007553             27.311725                   78.117553                      6061.630469
-27.165108           78.015053             27.215108                   78.065053                      6046.806490
                                           27.225108                   78.075053                      6047.919478
-27.163303           78.057044             27.203303                   78.097044                      6045.292278
                                           27.233303                   78.127044                      6048.631240
-27.161850           78.040165             27.271850                   78.150165                      6052.762693
-27.160832           78.011608             27.200832                   78.051608                      6044.742752
                                           27.250832                   78.101608                      6050.308632
                                           27.300832                   78.151608                      6055.879212
-26.490950           80.318656             26.530950                   80.358656                      5895.767837
-26.483042           80.317833             26.513042                   80.347833                      5892.896549
-26.482581           80.315628             26.502581                   80.335628                      5891.681591
                                           26.532581                   80.365628                      5895.019482
-26.481547           80.299775             26.541547                   80.359775                      5895.902549
                                           26.551547                   80.369775                      5897.015762
-26.479108           80.315042             26.519108                   80.355042                      5893.134297
-26.474986           80.342796             26.584986                   80.452796                      5900.011454
-26.474133           80.348100             26.484133                   80.358100                      5888.690600
Name: distance, dtype: float64

In [43]:
# droping those lattitude and longitude which are less than and above to
# latitude of india is 8°4` N  to 37°6` North
# longitude of india is 68°7` E to 97°25` East

In [44]:
df[(df['Restaurant_latitude'] < 8) & (df['Delivery_location_latitude'] < 8)].shape

# these 3509 record is of no use. bcz the wrong lattitude is mention

(3509, 26)

In [45]:
df = df.drop(df[(df['Restaurant_latitude'] < 8) & (df['Delivery_location_latitude'] < 8)].index)

In [46]:
df[(df['Restaurant_latitude'] > 37) & (df['Delivery_location_latitude'] > 37)]

Empty DataFrame
Columns: [Delivery_person_ID, Delivery_person_Ratings, Restaurant_latitude, Restaurant_longitude, Delivery_location_latitude, Delivery_location_longitude, Time_Orderd, Time_Order_picked, Weather_conditions, Road_traffic_density, Vehicle_condition, Type_of_order, Type_of_vehicle, multiple_deliveries, Festival, City, Time_taken (min), year, month, day, TimeOrder_Hour, TimeOrder_min, Time_Order_picked_Hour, Time_Order_picked_min, Delivery_city, distance]
Index: []

[0 rows x 26 columns]

In [47]:
#maximum distance

In [48]:
min_distance=df.groupby('distance')[['Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude',
                        'Delivery_location_longitude']].min().sort_values(by='distance',ascending=True).head(1)
min_distance

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude
distance,,,,
1.465067,30.914057,75.83982,30.924057,75.84982

In [49]:
numerical_feature=[feature for feature in df.columns if df[feature].dtypes != 'O']
numerical_feature

['Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Vehicle_condition',
 'multiple_deliveries',
 'Time_taken (min)',
 'year',
 'month',
 'day',
 'TimeOrder_Hour',
 'TimeOrder_min',
 'Time_Order_picked_Hour',
 'Time_Order_picked_min',
 'distance']

In [50]:
df.drop('Delivery_person_ID',axis=1,inplace=True)

In [51]:
df.drop(['Time_Orderd','Time_Order_picked'],axis=1,inplace=True)

In [52]:
num_col=[feature for feature in df.columns if df[feature].dtypes != 'O']
cat_col=[feature for feature in df.columns if df[feature].dtypes == 'O']

In [53]:
num_col

['Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Vehicle_condition',
 'multiple_deliveries',
 'Time_taken (min)',
 'year',
 'month',
 'day',
 'TimeOrder_Hour',
 'TimeOrder_min',
 'Time_Order_picked_Hour',
 'Time_Order_picked_min',
 'distance']

In [54]:
cat_col

['Weather_conditions',
 'Road_traffic_density',
 'Type_of_order',
 'Type_of_vehicle',
 'Festival',
 'City',
 'Delivery_city']

In [55]:
df.drop(['Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude','Delivery_location_longitude',
        'year','month','day','TimeOrder_min','Time_Order_picked_Hour','Time_Order_picked_min'],axis=1,inplace=True)

In [56]:
X = df.drop(labels=['Time_taken (min)'],axis=1)
y = df[['Time_taken (min)']]

In [57]:
df[cat_col].head()

,Weather_conditions,Road_traffic_density,Type_of_order,Type_of_vehicle,Festival,City,Delivery_city
0,Fog,Jam,Snack,motorcycle,No,Metropolitian,DEH
1,Stormy,High,Meal,motorcycle,No,Metropolitian,KOC
2,Sandstorms,Medium,Drinks,scooter,No,Metropolitian,PUNE
3,Sandstorms,Low,Buffet,motorcycle,No,Metropolitian,LUDH
4,Fog,Jam,Snack,scooter,No,Metropolitian,KNP

In [58]:
num_col=[feature for feature in df.columns if df[feature].dtypes != 'O']

In [59]:
df[num_col].head()

,Delivery_person_Ratings,Vehicle_condition,multiple_deliveries,Time_taken (min),TimeOrder_Hour,distance
0,4.2,2,3.0,46,21,10.280582
1,4.7,1,1.0,23,14,6.242319
2,4.7,1,1.0,21,17,13.787860
3,4.3,0,0.0,20,9,2.930258
4,4.7,1,1.0,41,19,19.396618

In [60]:
df[df['Road_traffic_density']=='Low']

,Delivery_person_Ratings,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),TimeOrder_Hour,Delivery_city,distance
3,4.3,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,9,LUDH,2.930258
11,4.7,Sandstorms,Low,2,Meal,electric_scooter,0.0,No,Metropolitian,26,22,RANCHI,19.618739
12,5.0,Sandstorms,Low,1,Snack,motorcycle,1.0,No,Metropolitian,20,8,COIMB,1.558132
17,4.3,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,38,23,SUR,13.682045
19,4.8,Windy,Low,2,Buffet,electric_scooter,0.0,No,Urban,12,23,PUNE,16.853619
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45569,4.9,Windy,Low,1,Snack,motorcycle,1.0,No,Metropolitian,26,10,COIMB,3.116127
45571,4.9,Sandstorms,Low,1,Snack,scooter,1.0,No,NaN,26,9,MYS,3.109134
45573,4.6,Cloudy,Low,0,Meal,motorcycle,0.0,No,Metropolitian,20,0,PUNE,3.064267
45575,4.8,Sandstorms,Low,2,Drinks,electric_scooter,0.0,No,Metropolitian,20,9,CHEN,3.104827
45581,4.9,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,23,CHEN,4.657195

In [61]:
Road_traffic_density=['Low','Medium','High','Jam']
Weather_conditions=['Sunny','Cloudy','Windy','Fog','Sandstorms','Stormy']

In [62]:
categorical_column=['Type_of_order','Type_of_vehicle','Festival','City','Delivery_city']
ordinal_encod=['Road_traffic_density','Weather_conditions']
numerical_column=['Delivery_person_Ratings','Vehicle_condition','multiple_deliveries',
                  'TimeOrder_Hour','distance']

In [63]:
# numerical pipeline

numerical_pipeline=Pipeline(steps=[
    ('impute',SimpleImputer(strategy='constant',fill_value=0)),
    ('scaler',StandardScaler(with_mean=False))
])

# categorical pipeline

categorical_pipeline=Pipeline(steps=[
    ('impute',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore')),
    ('scaler',StandardScaler(with_mean=False))
])


# ordinal pipeline

ordianl_pipeline=Pipeline(steps=[
    ('impute',SimpleImputer(strategy='most_frequent')),
    ('ordinal',OrdinalEncoder(categories=[Road_traffic_density,Weather_conditions])),
    ('scaler',StandardScaler(with_mean=False))   
])

In [64]:
preprocessor =ColumnTransformer([
    ('numerical_pipeline',numerical_pipeline,numerical_column),
    ('categorical_pipeline',categorical_pipeline,categorical_column),
    ('ordianl_pipeline',ordianl_pipeline,ordinal_encod)
])

In [65]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [66]:
X_train=preprocessor.fit_transform(X_train)

In [67]:
X_test=preprocessor.transform(X_test)

In [70]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\pcs\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\pcs\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
    --------------------------------------- 1.3/101.7 MB 3.7 MB/s eta 0:00:28
   - -------------------------------------- 2.9/101.7 MB 5.4 MB/s eta 0:00:19
   - -------------------------------------- 4.5/101.7 MB 6.1 MB/s eta 0:00:17
   -- ------------------------------------- 6.0/101.7 MB 6.5 MB/s eta 0:00:15
   -- ------------------------------------- 7.6/101.7 MB 6.6 MB/s eta 0:00:15
   --- ------------------------------------ 8.9/101.7 MB 6.7 MB/s eta 0:00:14
   ---- ----------------------------------- 10.7/101.7 MB 6.8 MB/s eta 0:00:14
   ---- ----------------------------------- 12.1/101.7 MB 6.8 MB/s eta 0:00:14
   ----- ---------------------------------- 13.9/101.7 MB 6.9 MB/s eta 0:00:13
   ----- ---------------------------------- 15.2/101.7 MB 6.8 MB/s eta 0:00:13
   ------ --------------------------------- 16.8/101.7 MB 6.8 MB/s eta 0:00:13
   ------- -------------------------------- 18.6/101.7 MB 6.9 MB/s eta 0:00:13
   -------- ------------------------------- 21.0/101.7 MB 7.1 MB/s eta 0:00:12
   -------- ------------------------------- 22.5/101.7 MB 7.1 MB/s eta 0:00:12
   --------- ------------------------------ 24.1/101.7 MB 7.1 MB/s eta 0:00:11
   ---------- ----------------------------- 25.7/101.7 MB 7.2 MB/s eta 0:00:11
   ---------- ----------------------------- 27.5/101.7 MB 7.2 MB/s eta 0:00:11
   ----------- ---------------------------- 29.1/101.7 MB 7.2 MB/s eta 0:00:11
   ------------ --------------------------- 30.9/101.7 MB 7.3 MB/s eta 0:00:10
   ------------ --------------------------- 32.8/101.7 MB 7.3 MB/s eta 0:00:10
   ------------- -------------------------- 34.3/101.7 MB 7.3 MB/s eta 0:00:10
   -------------- ------------------------- 36.2/101.7 MB 7.3 MB/s eta 0:00:10
   -------------- ------------------------- 37.7/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 39.3/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 39.8/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 39.8/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 39.8/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 39.8/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 39.8/101.7 MB 7.3 MB/s eta 0:00:09
   --------------- ------------------------ 40.6/101.7 MB 6.1 MB/s eta 0:00:11
   ---------------- ----------------------- 41.4/101.7 MB 6.0 MB/s eta 0:00:11
   ---------------- ----------------------- 41.7/101.7 MB 5.9 MB/s eta 0:00:11
   ---------------- ----------------------- 41.9/101.7 MB 5.8 MB/s eta 0:00:11
   ---------------- ----------------------- 43.0/101.7 MB 5.7 MB/s eta 0:00:11
   ----------------- ---------------------- 44.6/101.7 MB 5.7 MB/s eta 0:00:11
   ------------------ --------------------- 45.9/101.7 MB 5.7 MB/s eta 0:00:10
   ------------------ --------------------- 47.2/101.7 MB 5.7 MB/s eta 0:00:10
   ------------------ --------------------- 48.2/101.7 MB 5.7 MB/s eta 0:00:10
   ------------------- -------------------- 49.5/101.7 MB 5.7 MB/s eta 0:00:10
   ------------------- -------------------- 50.6/101.7 MB 5.7 MB/s eta 0:00:09
   -------------------- ------------------- 51.4/101.7 MB 5.7 MB/s eta 0:00:09
   -------------------- ------------------- 52.4/101.7 MB 5.6 MB/s eta 0:00:09
   -------------------- ------------------- 53.0/101.7 MB 5.6 MB/s eta 0:00:09
   --------------------- ------------------ 53.5/101.7 MB 5.5 MB/s eta 0:00:09
   --------------------- ------------------ 53.5/101.7 MB 5.5 MB/s eta 0:00:09
   --------------------- ------------------ 55.1/101.7 MB 5.4 MB/s eta 0:00:09
   --------------------- ------------------ 55.3/101.7 MB 5.4 MB/s eta 0:00:09
   --------------------- ------------------ 55.3/101.7 MB 5.4 MB/s eta 0:00:09
   ---------------------- ----------------- 56.9/101.7 MB 5.2 MB/s eta 0:00:09
   ---------------------- ----------------- 57.7/101.7 MB 5.2 MB/s eta 0:00:09
   ----------------------- ---------------- 58.7/101.7 MB 5.2 MB/s eta 0:00:09
   ----------------------- ---------------- 59.8/101.7 MB 5.2 MB/s eta 0:00:09
   ------------------------ --------------- 61.1/101.7 MB 5.2 MB/s eta 0:00:08
   ------------------------ --------------- 62.1/101.7 MB 5.2 MB/s eta 0:00:08
   ------------------------ --------------- 63.4/101.7 MB 5.2 MB/s eta 0:00:08
   ------------------------- -------------- 64.5/101.7 MB 5.2 MB/s eta 0:00:08
   ------------------------- -------------- 65.5/101.7 MB 5.2 MB/s eta 0:00:07
   -------------------------- ------------- 66.8/101.7 MB 5.2 MB/s eta 0:00:07
   -------------------------- ------------- 68.2/101.7 MB 5.2 MB/s eta 0:00:07
   --------------------------- ------------ 69.2/101.7 MB 5.2 MB/s eta 0:00:07
   --------------------------- ------------ 70.5/101.7 MB 5.2 MB/s eta 0:00:06
   ---------------------------- ----------- 71.8/101.7 MB 5.2 MB/s eta 0:00:06
   ---------------------------- ----------- 72.9/101.7 MB 5.3 MB/s eta 0:00:06
   ----------------------------- ---------- 74.2/101.7 MB 5.3 MB/s eta 0:00:06
   ----------------------------- ---------- 75.5/101.7 MB 5.3 MB/s eta 0:00:05
   ------------------------------ --------- 76.3/101.7 MB 5.3 MB/s eta 0:00:05
   ------------------------------ --------- 77.1/101.7 MB 5.2 MB/s eta 0:00:05
   ------------------------------ --------- 77.3/101.7 MB 5.2 MB/s eta 0:00:05
   ------------------------------ --------- 77.3/101.7 MB 5.2 MB/s eta 0:00:05
   ------------------------------ --------- 78.1/101.7 MB 5.1 MB/s eta 0:00:05
   ------------------------------ --------- 78.6/101.7 MB 5.1 MB/s eta 0:00:05
   ------------------------------- -------- 78.9/101.7 MB 5.0 MB/s eta 0:00:05
   ------------------------------- -------- 78.9/101.7 MB 5.0 MB/s eta 0:00:05
   ------------------------------- -------- 79.7/101.7 MB 4.9 MB/s eta 0:00:05
   ------------------------------- -------- 80.2/101.7 MB 4.9 MB/s eta 0:00:05
   ------------------------------- -------- 81.0/101.7 MB 4.8 MB/s eta 0:00:05
   -------------------------------- ------- 81.5/101.7 MB 4.8 MB/s eta 0:00:05
   -------------------------------- ------- 82.3/101.7 MB 4.8 MB/s eta 0:00:05
   -------------------------------- ------- 83.1/101.7 MB 4.8 MB/s eta 0:00:04
   -------------------------------- ------- 83.9/101.7 MB 4.8 MB/s eta 0:00:04
   --------------------------------- ------ 84.7/101.7 MB 4.8 MB/s eta 0:00:04
   --------------------------------- ------ 85.5/101.7 MB 4.7 MB/s eta 0:00:04
   --------------------------------- ------ 86.0/101.7 MB 4.7 MB/s eta 0:00:04
   ---------------------------------- ----- 87.0/101.7 MB 4.7 MB/s eta 0:00:04
   ---------------------------------- ----- 87.6/101.7 MB 4.7 MB/s eta 0:00:04
   ---------------------------------- ----- 88.1/101.7 MB 4.7 MB/s eta 0:00:03
   ---------------------------------- ----- 88.9/101.7 MB 4.7 MB/s eta 0:00:03
   ----------------------------------- ---- 89.7/101.7 MB 4.6 MB/s eta 0:00:03
   ----------------------------------- ---- 90.4/101.7 MB 4.6 MB/s eta 0:00:03
   ----------------------------------- ---- 91.2/101.7 MB 4.6 MB/s eta 0:00:03
   ------------------------------------ --- 92.0/101.7 MB 4.6 MB/s eta 0:00:03
   ------------------------------------ --- 92.5/101.7 MB 4.6 MB/s eta 0:00:02
   ------------------------------------ --- 93.3/101.7 MB 4.6 MB/s eta 0:00:02
   ------------------------------------- -- 94.1/101.7 MB 4.6 MB/s eta 0:00:02
   ------------------------------------- -- 94.9/101.7 MB 4.6 MB/s eta 0:00:02
   ------------------------------------- -- 95.9/101.7 MB 4.6 MB/s eta 0:00:02
   ------------------------------------- -- 96.5/101.7 MB 4.5 MB/s eta 0:00:02
   -------------------------------------- - 97.3/101.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 98.0/101.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 98.8/101.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  99.6/101.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  101.2/101.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 4.4 MB/s  0:00:23
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [71]:
from sklearn.linear_model import LinearRegression

from sklearn.linear_model import Lasso,Ridge,ElasticNet
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor 

from xgboost import XGBRegressor



from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [72]:
def evaluate_reg(true, predicted):
    r2 = r2_score(true, predicted) # Calculate r2 score
    MAE = mean_absolute_error(true, predicted) # Calculate MAE
    MSE = mean_squared_error(true, predicted) # Calculate MSE
    rmse = np.sqrt(mean_squared_error(true, predicted))
   
    return r2, MAE , MSE,rmse

In [73]:
models = {
    "Random Forest": RandomForestRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Gradient Boosting": GradientBoostingRegressor(),
    "linear Regression": LinearRegression(),
    "Ridge":Ridge(),
    "XGBRegressor": XGBRegressor(), 
  
}

r2_list=[]
mse_list=[]
models_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    

    
    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)



    # Test set performance
    r2,MAE,MSE,rmse=evaluate_reg(y_test, y_test_pred)
    r2_train,MAE_train,MSE_train,rmse_train=evaluate_reg(y_train, y_train_pred)
    

    print(list(models.keys())[i])
    models_list.append(list(models.keys())[i])
    

    
    print('Model performance for Test set')
    print('- r2_score: {:.4f}'.format(r2))
    print('- MAE: {:.4f}'.format(MAE))
    print('- MSE: {:.4f}'.format(MSE))
    print('- rmse: {:.4f}'.format(rmse))
    r2_list.append(r2)
    mse_list.append(MSE)
    
    print('-'*35)
        
    print('Model performance for train set')
    print('- r2_score: {:.4f}'.format(r2_train))
    print('- MAE: {:.4f}'.format(MAE_train))
    print('- MSE: {:.4f}'.format(MSE_train))
    print('- rmse: {:.4f}'.format(rmse_train))

    print('='*35)
    print('='*35)
    print('\n')

Random Forest
Model performance for Test set
- r2_score: 0.7034
- MAE: 4.0204
- MSE: 26.4694
- rmse: 5.1448
-----------------------------------
Model performance for train set
- r2_score: 0.9595
- MAE: 1.4537
- MSE: 3.5436
- rmse: 1.8825
===================================
===================================


Decision Tree
Model performance for Test set
- r2_score: 0.4644
- MAE: 5.2768
- MSE: 47.8032
- rmse: 6.9140
-----------------------------------
Model performance for train set
- r2_score: 0.9999
- MAE: 0.0027
- MSE: 0.0109
- rmse: 0.1043
===================================
===================================


Gradient Boosting
Model performance for Test set
- r2_score: 0.6867
- MAE: 4.1875
- MSE: 27.9611
- rmse: 5.2878
-----------------------------------
Model performance for train set
- r2_score: 0.6963
- MAE: 4.0852
- MSE: 26.5630
- rmse: 5.1539
===================================
===================================


linear Regression
Model performance for Test set
- r2_score: 0.4562
- MAE: 5.5527
- MSE: 48.5409
- rmse: 6.9671
-----------------------------------
Model performance for train set
- r2_score: 0.4643
- MAE: 5.4277
- MSE: 46.8621
- rmse: 6.8456
===================================
===================================


Ridge
Model performance for Test set
- r2_score: 0.4562
- MAE: 5.5527
- MSE: 48.5409
- rmse: 6.9671
-----------------------------------
Model performance for train set
- r2_score: 0.4643
- MAE: 5.4277
- MSE: 46.8621
- rmse: 6.8456
===================================
===================================


XGBRegressor
Model performance for Test set
- r2_score: 0.7201
- MAE: 3.9478
- MSE: 24.9793
- rmse: 4.9979
-----------------------------------
Model performance for train set
- r2_score: 0.7953
- MAE: 3.3004
- MSE: 17.9037
- rmse: 4.2313
===================================
===================================

In [74]:
Results = pd.DataFrame(list(zip(models_list, r2_list)), columns=['Model Name', 'r2_score'])
Results.sort_values(by=["r2_score"],ascending=False)

          Model Name  r2_score
5       XGBRegressor  0.720140
0      Random Forest  0.703446
2  Gradient Boosting  0.686734
1      Decision Tree  0.464429
3  linear Regression  0.456164
4              Ridge  0.456164

In [75]:
Results = pd.DataFrame(list(zip(models_list, mse_list)), columns=['Model Name', 'Mse'])
Results.sort_values(by=["Mse"],ascending=True)

          Model Name        Mse
5       XGBRegressor  24.979334
0      Random Forest  26.469353
2  Gradient Boosting  27.961070
1      Decision Tree  47.803166
3  linear Regression  48.540876
4              Ridge  48.540910